version: '3.9'

services:
  mafaniabot:
    container_name: mafaniabot-dev
    image: mafaniabot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PORT=5000
    ports:
      - "5000:5000"
    links:
      - redis

  redis:
    container_name: redis-dev
    image: redis
    command: redis-server --appendonly yes
    volumes:
    - ./redisdata:/data
