version: '3.7'

services:
  mafaniabot:
    image: mafaniabot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PORT=5000
    ports:
      - "5000:5000"

  redis:
    image: redis
